syntax = "proto3";
package stoc.stoc;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "stoc/stoc/params.proto";
import "stoc/stoc/token.proto";

option go_package = "stoc/x/stoc/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a (governance) operation for updating the module
  // parameters. The authority defaults to the x/gov module account.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  //CreateToken creates a new token
  rpc CreateToken(MsgCreateToken) returns (MsgCreateTokenResponse); 

  //ReleaseTokens releases tokens to a recipient
  rpc ReleaseTokens(MsgReleaseTokens) returns (MsgReleaseTokensResponse);

  //MintTokens mints tokens to a recipient
  rpc MintTokens(MsgMintTokens) returns (MsgMintTokensResponse);

  //BurnToken burns tokens
  rpc BurnToken(MsgBurnToken) returns (MsgBurnTokenResponse);
}

// MsgUpdateParams is the Msg/UpdateParams request type.
message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "stoc/x/stoc/MsgUpdateParams";

  // authority is the address that controls the module (defaults to x/gov unless overwritten).
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  // params defines the module parameters to update.
  //
  // NOTE: All parameters must be supplied.
  Params params = 2 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

//MsgCreateToken defiends the message for creating a new token
message MsgCreateToken{
  option(cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string name = 2;
  string symbol = 3;
  string initial_supply = 4 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int", 
    (gogoproto.nullable) = false
  ];
  string total_supply = 5 [
    (gogoproto.customtype) = "cosmossdk.io/math.Int", 
    (gogoproto.nullable) = false
  ];
  uint32 decimals = 6;
  string logo = 7;
  repeated WalletDistribution distributions = 8 [(gogoproto.nullable) = false];
  TokenTax tax = 9 [(gogoproto.nullable) = false];
  bool unlimited = 10;
}

message MsgReleaseTokens {
  option(cosmos.msg.v1.signer) = "creator";
  
  string creator = 1;
  string symbol = 2;
  string amount = 3 [(gogoproto.customtype) = "cosmossdk.io/math.Int", (gogoproto.nullable) = false];
  string recipient = 4;
}

message MsgMintTokens {
  option(cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string symbol = 2;
  string amount = 3 [(gogoproto.customtype) = "cosmossdk.io/math.Int", (gogoproto.nullable) = false];
}
message MsgReleaseTokensResponse{
  string symbol = 1;
  string amount = 2;
  string recipient = 3;
  bool success = 4;
  string message = 5;
}

message MsgCreateTokenResponse{
  string symbol = 1;
  string creator = 2;
  bool success = 3;
  string message = 4;
}

message MsgMintTokensResponse{
  string symbol = 1;
  string amount = 2;
  string recipient = 3;
  bool success = 4;
  string message = 5;
}

message MsgBurnToken {
  option (cosmos.msg.v1.signer) = "creator";

  string creator = 1;
  string amount = 2 [(gogoproto.customtype) = "cosmossdk.io/math.Int", (gogoproto.nullable) = false];
  string denom = 3;
  bool burn_all = 4;
}

message MsgBurnTokenResponse {
  bool success = 1;
  string message = 2;
}
// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
message MsgUpdateParamsResponse {}